version: '3.1'

services:
  cakeblog-web:
    build: .
    image: cakeblog-php
    container_name: cakeblog-web
    volumes:
      - ./:/var/www/html/public
    ports:
      - 8181:80
    networks:
      - cakeblognet

  cakeblog-db:
    image: mysql:5.7
    container_name: cakeblog-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakeblog-db
      MYSQL_USER: cakeblog
      MYSQL_PASSWORD: cakeblog
    ports:
      - 3505:3306
    networks:
      - cakeblognet

networks:
  cakeblognet:
      driver: bridge
